---
swagger: "2.0"
info:
  title: "ebox federation"
  version: "1.3"
  description: "API that focuses on central information inside the ebox Federation."
  contact:
    name: "ebox Integration"
    url: "https://www.eboxenterprise.be"
    email: "eboxintegration@smals.be"
basePath: "/REST/ebox/enterprise/federation/v1"
securityDefinitions:
  oauth2:
    type: "oauth2"
    authorizationUrl: "https://*.socialsecurity.be/oauth2/authorize"
    flow: "implicit"
    scopes:
      "scope:documentmanagement:ebox:enterprise:federation-rest:registry": "Consult provider registry"
      "scope:documentmanagement:ebox:enterprise:federation-rest:preference": "Consult eBox preferences"
tags:
- name: "EboxPreferences"
- name: "MessageProviders"
- name: "Documentation"
schemes:
- "https"
paths:
  /api:
    get:
      tags:
      - "Documentation"
      summary: "List links"
      description: ""
      operationId: "get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/HalResource"
          headers:
            Link:
              type: "string"
              description: "RFC 5988 Link Header"
    options:
      tags:
      - "Documentation"
      summary: "List links"
      description: ""
      operationId: "options"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/HalResource"
          headers:
            Link:
              type: "string"
              description: "RFC 5988 Link Header"
  /api/doc:
    get:
      tags:
      - "Documentation"
      summary: "Returns the API documentation in HTML format"
      description: ""
      operationId: "getApiDoc"
      produces:
      - "text/html"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
  /api/doc/jsonSchemas/{jsonSchema}:
    get:
      tags:
      - "Documentation"
      summary: "Returns the JSON Schemas"
      description: ""
      operationId: "getJsonSchema"
      produces:
      - "application/json"
      parameters:
      - name: "jsonSchema"
        in: "path"
        description: "JSON Schema name"
        required: true
        type: "string"
        pattern: ".+"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
  /api/doc/swagger.json:
    get:
      tags:
      - "Documentation"
      summary: "Returns the API documentation in JSON Swagger format"
      description: ""
      operationId: "getSwagger"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
  /eboxPreferences/search:
    post:
      tags:
      - "EboxPreferences"
      summary: "Consult the EboxPreferences by posting a list of eboxIds."
      operationId: "getEboxPreferencesByList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "eboxIdSameTypeList"
        description: "List of eboxIds"
        schema:
          $ref: "#/definitions/EboxIdSameTypeList"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/EboxPreferencesList"
        400:
          description: "Invalid acess token"
          schema:
            $ref: "#/definitions/StatusMessage"
        401:
          description: "Invalid authorization for ebox"
          schema:
            $ref: "#/definitions/StatusMessage"
        404:
          description: "Ebox not found"
          schema:
            $ref: "#/definitions/StatusMessage"
  /eboxPreferences:
    patch:
      tags:
      - "EboxPreferences"
      summary: "Update certain properties of EboxPreferences for a given ebox."
      operationId: "patchEboxPreferencesById"
      consumes:
        - "application/merge-patch+json"
      produces:
      - "application/json"
      parameters:
      - name: "eboxPreferencesToUpdate"
        in: "body"
        description: "The eboxPreferences for a given ebox."
        required: true
        schema:
          $ref: "#/definitions/EboxPreferencesToUpdate"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/EboxPreferences"
        400:
          description: "Invalid acess token"
          schema:
            $ref: "#/definitions/StatusMessage"
        401:
          description: "Invalid authorization for ebox"
          schema:
            $ref: "#/definitions/StatusMessage"
        404:
          description: "Ebox not found"
          schema:
            $ref: "#/definitions/StatusMessage"
  /messageProviders:
    get:
      tags:
      - "MessageProviders"
      summary: "List all message providers of the federated ebox."
      description: ""
      operationId: "findAllMessageProviders"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/MessageProviderList"
        404:
          description: "MessageProviders not found"
          schema:
            $ref: "#/definitions/StatusMessage"
  /messageProviders/{messageProviderId}:
    get:
      tags:
      - "MessageProviders"
      summary: "Get a messageProvider by its messageProviderId"
      description: ""
      operationId: "getMessageProviderById"
      produces:
      - "application/json"
      parameters:
      - name: "messageProviderId"
        in: "path"
        description: "The messageProviderId of the provider"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/MessageProvider"
        400:
          description: "Invalid messageProviderId supplied"
          schema:
            $ref: "#/definitions/StatusMessage"
        404:
          description: "MessageProviderId not found"
          schema:
            $ref: "#/definitions/StatusMessage"
    patch:
      tags:
      - "MessageProviders"
      summary: "Update a messageProvider."
      operationId: "patchMessageProviderById"
      consumes:
        - "application/merge-patch+json"
      produces:
      - "application/json"
      parameters:
      - name: "messageProviderId"
        in: "path"
        description: "The Id of the messageProvider to update."
        required: true
        type: "string"
      - in: "body"
        name: "MessageProvider"
        description: "The MessageProvider to update."
        schema:
          $ref: "#/definitions/MessageProvider"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/MessageProvider"
        400:
          description: "Invalid acess token"
          schema:
            $ref: "#/definitions/StatusMessage"
        401:
          description: "Invalid authorization for ebox"
          schema:
            $ref: "#/definitions/StatusMessage"
        404:
          description: "Ebox not found"
          schema:
            $ref: "#/definitions/StatusMessage"
definitions:
  Detail:
    type: "object"
    properties:
      kind:
        type: "object"
      message:
        type: "object"
      ref:
        type: "object"
      value:
        type: "object"
  EboxId:
    type: "object"
    required:
    - "eboxType"
    - "eboxIdValue"
    properties:
      eboxType:
        type: "string"
        example: "ENTERPRISE"
      eboxIdValue:
        type: "string"
        example: "0406798006"
  EboxIdSameTypeList:
    type: "object"
    required:
    - "eboxType"
    - "eboxIdType"
    - "eboxIdValueList"
    properties:
      eboxType:
        type: "string"
        example: "ENTERPRISE"
      eboxIdType:
        type: "string"
        example: "EnterpriseNumber"
      eboxIdValueList:
        type: "array"
        items:
          type: "string"
          example: "0406798006"
  EboxPreferences:
    type: "object"
    required:
    - "eboxId"
    - "exclusivelyEbox"
    properties:
      eboxId:
        $ref: "#/definitions/EboxId"
      exclusivelyEbox:
        type: "boolean"
        description: "Indication if the enterprise/citizen has chosen to use the ebox as the exclusive channel (Do not send a paper copy anymore)."
        example: true
      lastConnectionDate:
        description: "Most recently date-time when a user has been connected to its ebox using official GUI."
        type: "string"
        format: "date-time"
        example: "2019-04-19T20:00:00Z"
      totalNumberOfMessages:
        description: "Sum of all messages for every document provider"
        type: "integer"
        example: "999"
      totalNumberOfUnreadMessages:
        description: "Sum of all unread messages for every document provider"
        type: "integer"
        example: "3"
  EboxPreferencesToUpdate:
    type: "object"
    required:
    - "eboxId"
    - "exclusivelyEbox"
    properties:
      eboxId:
        $ref: "#/definitions/EboxId"
      exclusivelyEbox:
        type: "boolean"
        description: "Indication if the enterprise/citizen has chosen to use the ebox as the exclusive channel (Do not send a paper copy anymore)."
        example: true
  EboxPreferencesList:
    type: "array"
    description: "A list of EboxPreferences"
    items:
      $ref: "#/definitions/EboxPreferences"
  HalLink:
    type: "object"
    required:
    - "href"
    properties:
      href:
        type: "string"
        format: "uri"
        description: "Its value is either a URI [RFC3986] or a URI Template [RFC6570]."
      hreflang:
        type: "string"
        description: "When present, is a hint in RFC5646 format indicating what the\
          \ language of the result of dereferencing the link should be.  Note that\
          \ this is only a hint; for example, it does not override the Content-Language\
          \ header of a HTTP response obtained by actually following the link."
        pattern: "^([a-zA-Z]{2,3}(-[a-zA-Z]{3}(-[a-zA-Z]{3}){0,2})?(-[a-zA-Z]{4})?(-([a-zA-Z]{2}|[0-9]{3}))?(-([a-zA-Z0-9]{5,8}|[0-9][a-zA-Z0-9]{3}))*([0-9A-WY-Za-wy-z](-[a-zA-Z0-9]{2,8}){1,})*(x-[a-zA-Z0-9]{2,8})?)|(x-[a-zA-Z0-9]{2,8})|(en-GB-oed)|(i-ami)|(i-bnn)|(i-default)|(i-enochian)|(i-hak)|(i-klingon)|(i-lux)|(i-mingo)|(i-navajo)|(i-pwn)|(i-tao)|(i-tay)|(i-tsu)|(sgn-BE-FR)|(sgn-BE-NL)|(sgn-CH-DE)|(art-lojban)|(cel-gaulish)|(no-bok)|(no-nyn)|(zh-guoyu)|(zh-hakka)|(zh-min)|(zh-min-nan)|(zh-xiang)$"
      templated:
        type: "boolean"
        description: "Its value is boolean and SHOULD be true when the Link Object's\
          \ href property is a URI Template."
        default: false
      type:
        type: "string"
        description: "Its value is a string used as a hint to indicate the media type\
          \ expected when dereferencing the target resource."
      deprecation:
        type: "boolean"
        description: "Its presence indicates that the link is to be deprecated (i.e.\
          \ removed) at a future date. Its value is a URL that SHOULD provide further\
          \ information about the deprecation."
        default: false
      name:
        type: "string"
        description: "Its value MAY be used as a secondary key for selecting Link\
          \ Objects which share the same relation type."
      title:
        type: "string"
        description: "Its value is a string and is intended for labelling the link\
          \ with a human-readable identifier (as defined by [RFC5988])."
  HalLinks:
    type: "object"
    properties:
      self:
        $ref: "#/definitions/HalLink"
    description: "Object of links with the rels as the keys"
  HalResource:
    type: "object"
    properties:
      _links:
        description: "Object of links with the rels as the keys"
        $ref: "#/definitions/HalLinks"
    description: "A resource modeled after the HAL specification"
  MessageProvider:
    type: "object"
    required:
    - "messageProviderActivationDate"
    - "messageProviderDescription"
    - "messageProviderId"
    - "messageProviderName"
    - "messageProviderTechnicalContact"
    - "messageProviderUrl"
    - "apiSupportedVersion"
    properties:
      messageProviderId:
        type: "string"
        description: "Identifier of the messageProvider"
        minLength: 1
        maxLength: 100
      messageProviderName:
        description: "Common type defined to provide a string value for each supported\
          \ language among nl, fr, de, en"
        $ref: "#/definitions/TranslatedString"
      messageProviderDescription:
        description: "Common type defined to provide a string value for each supported\
          \ language among nl, fr, de, en"
        $ref: "#/definitions/TranslatedString"
      messageProviderUrl:
        type: "string"
        example: "http://ebox-citizen-rest.int.paas.socialsecurity.be/REST/ebox/citizen/v2/"
        description: "The URL to the messageProvider implementation"
      messageProviderActivationDate:
        type: "string"
        format: "date"
        example: "2017-12-01"
        description: "Activation date of the service. Services should be ignored when\
          \ they are not yet activated."
      messageProviderDeactivationDate:
        type: "string"
        format: "date"
        example: "2018-01-01"
        description: "Deactivation date of the service. Services should be ignored\
          \ when they are deactivated."
      messageProviderTechnicalContact:
        type: "string"
        example: "eboxintegration@smals.be"
        description: "Contact information for technical questions concerning the implementation\
          \ of the REST service by the provider"
      messageProviderPlannedMaintenance:
        type: "array"
        description: "List of dateIntervals on which the REST service of the provider\
          \ will be unavailable due to maintenance"
        items:
          $ref: "#/definitions/MessageProviderPlannedMaintenance"
      apiSupportedVersion:
        type: "string"
        example: "1.6"
        description: "Version number of the API implemented by the messageProvider."
      _links:
        description: "Object of links with the rels as the keys"
        $ref: "#/definitions/HalLinks"
    description: "Schema describing the messageProvider resource that returns the\
      \ necessary information concerning a messageResource"
  MessageProviderPlannedMaintenance:
    type: "object"
    required:
    - "endDate"
    - "startDate"
    properties:
      startDate:
        type: "string"
        format: "date-time"
        example: "2017-09-09T08:00:00Z"
        description: "Date and time from which the service will no longer be available\
          \ because of maintenance."
      endDate:
        type: "string"
        format: "date-time"
        example: "2017-09-09T20:00:00Z"
        description: "Date and time from which the service will be available again."
    description: "A date interval defined by a start date-time and an end date-time"
  MessageProviderList:
    description: "List of messageProviders"
    type: "array"
    items:
        $ref: "#/definitions/MessageProvider"
  StatusMessage:
    type: "object"
    required:
    - "code"
    - "id"
    - "message"
    properties:
      id:
        type: "string"
        format: "uuid"
      code:
        type: "string"
      message:
        type: "string"
      contact:
        type: "string"
      environment:
        type: "string"
        enum:
        - "DEVELOPMENT"
        - "TEST"
        - "INTEGRATION"
        - "ACCEPTATION"
        - "SIMULATION"
        - "PRODUCTION"
      stackTrace:
        type: "array"
        items:
          type: "array"
          items:
            type: "string"
      details:
        type: "array"
        items:
          $ref: "#/definitions/Detail"
    description: "A representation of a generic error message"
  TranslatedString:
    type: "object"
    properties:
      nl:
        type: "string"
      fr:
        type: "string"
      de:
        type: "string"
      en:
        type: "string"
    description: "Common type defined to provide a string value for each supported\
      \ language among nl, fr, de, en"
